// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openFile: () => typedError<FileData, string>(__TAURI_INVOKE("open_file")),
	saveFile: (path: string, content: string) => typedError<boolean, string>(__TAURI_INVOKE("save_file", { path, content })),
	saveFileAs: (content: string) => typedError<string | null, string>(__TAURI_INVOKE("save_file_as", { content })),
	readSettings: () => typedError<Settings, string>(__TAURI_INVOKE("read_settings")),
	writeSettings: (settings: Settings) => typedError<boolean, string>(__TAURI_INVOKE("write_settings", { settings })),
	getRecentFiles: () => typedError<string[], string>(__TAURI_INVOKE("get_recent_files")),
	// Чтение файла по пути (для открытия через ассоциацию файлов)
	readFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { path })),
	getPendingFile: () => __TAURI_INVOKE<string | null>("get_pending_file"),
};

/* Types */
export type FileData = {
	path: string,
	content: string,
};

export type Settings = {
	font_family?: string,
	font_size?: number,
	theme?: string,
	language?: string,
	recent_files?: string[],
	page_width?: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

